// @ts-nocheck
/* eslint-disable */
/* tslint:disable */
/* prettier-ignore-start */
/** @jsxRuntime classic */
/** @jsx createPlasmicElementProxy */
/** @jsxFrag React.Fragment */
// This class is auto-generated by Plasmic; please do not edit!
// Plasmic Project: xxLpVGLUUz3W9tP5obHKh2
// Component: xVI_0YNHH6
import * as React from "react";

import Head from "next/head";
import Link, { LinkProps } from "next/link";

import * as p from "@plasmicapp/react-web";
import {
  hasVariant,
  classNames,
  wrapWithClassName,
  createPlasmicElementProxy,
  makeFragment,
  MultiChoiceArg,
  SingleBooleanChoiceArg,
  SingleChoiceArg,
  pick,
  omit,
  useTrigger,
  StrictProps,
  deriveRenderOpts,
  ensureGlobalVariants
} from "@plasmicapp/react-web";

import "@plasmicapp/react-web/lib/plasmic.css";
import * as defaultcss from "../plasmic__default_style.module.css"; // plasmic-import: global/defaultcss
import * as projectcss from "./plasmic_mega_menu.module.css"; // plasmic-import: xxLpVGLUUz3W9tP5obHKh2/projectcss
import * as sty from "./PlasmicMenu1.module.css"; // plasmic-import: xVI_0YNHH6/css

export type PlasmicMenu1__VariantMembers = {};

export type PlasmicMenu1__VariantsArgs = {};
type VariantPropType = keyof PlasmicMenu1__VariantsArgs;
export const PlasmicMenu1__VariantProps = new Array<VariantPropType>();

export type PlasmicMenu1__ArgsType = {};
type ArgPropType = keyof PlasmicMenu1__ArgsType;
export const PlasmicMenu1__ArgProps = new Array<ArgPropType>();

export type PlasmicMenu1__OverridesType = {
  root?: p.Flex<"div">;
  box?: p.Flex<"div">;
};

export interface DefaultMenu1Props {
  className?: string;
}

function PlasmicMenu1__RenderFunc(props: {
  variants: PlasmicMenu1__VariantsArgs;
  args: PlasmicMenu1__ArgsType;
  overrides: PlasmicMenu1__OverridesType;
  forNode?: string;
}) {
  const { variants, args, overrides, forNode } = props;

  return (
    <div
      data-plasmic-name={"root"}
      data-plasmic-override={overrides.root}
      data-plasmic-root={true}
      data-plasmic-for-node={forNode}
      className={classNames(defaultcss.all, projectcss.root_reset, sty.root)}
    >
      <div
        data-plasmic-name={"box"}
        data-plasmic-override={overrides.box}
        className={classNames(defaultcss.all, defaultcss.__wab_text, sty.box)}
      >
        {"This is the first menu."}
      </div>
    </div>
  ) as React.ReactElement | null;
}

const PlasmicDescendants = {
  root: ["root", "box"],
  box: ["box"]
} as const;
type NodeNameType = keyof typeof PlasmicDescendants;
type DescendantsType<
  T extends NodeNameType
> = typeof PlasmicDescendants[T][number];
type NodeDefaultElementType = {
  root: "div";
  box: "div";
};

type ReservedPropsType = "variants" | "args" | "overrides";
type NodeOverridesType<T extends NodeNameType> = Pick<
  PlasmicMenu1__OverridesType,
  DescendantsType<T>
>;
type NodeComponentProps<T extends NodeNameType> = { // Explicitly specify variants, args, and overrides as objects
  variants?: PlasmicMenu1__VariantsArgs;
  args?: PlasmicMenu1__ArgsType;
  overrides?: NodeOverridesType<T>;
} & Omit<PlasmicMenu1__VariantsArgs, ReservedPropsType> & // Specify variants directly as props
  // Specify args directly as props
  Omit<PlasmicMenu1__ArgsType, ReservedPropsType> &
  // Specify overrides for each element directly as props
  Omit<
    NodeOverridesType<T>,
    ReservedPropsType | VariantPropType | ArgPropType
  > &
  // Specify props for the root element
  Omit<
    Partial<React.ComponentProps<NodeDefaultElementType[T]>>,
    ReservedPropsType | VariantPropType | ArgPropType | DescendantsType<T>
  >;

function makeNodeComponent<NodeName extends NodeNameType>(nodeName: NodeName) {
  type PropsType = NodeComponentProps<NodeName> & { key?: React.Key };
  const func = function <T extends PropsType>(
    props: T & StrictProps<T, PropsType>
  ) {
    const { variants, args, overrides } = deriveRenderOpts(props, {
      name: nodeName,
      descendantNames: [...PlasmicDescendants[nodeName]],
      internalArgPropNames: PlasmicMenu1__ArgProps,
      internalVariantPropNames: PlasmicMenu1__VariantProps
    });

    return PlasmicMenu1__RenderFunc({
      variants,
      args,
      overrides,
      forNode: nodeName
    });
  };
  if (nodeName === "root") {
    func.displayName = "PlasmicMenu1";
  } else {
    func.displayName = `PlasmicMenu1.${nodeName}`;
  }
  return func;
}

export const PlasmicMenu1 = Object.assign(
  // Top-level PlasmicMenu1 renders the root element
  makeNodeComponent("root"),
  {
    // Helper components rendering sub-elements
    box: makeNodeComponent("box"),

    // Metadata about props expected for PlasmicMenu1
    internalVariantProps: PlasmicMenu1__VariantProps,
    internalArgProps: PlasmicMenu1__ArgProps
  }
);

export default PlasmicMenu1;
/* prettier-ignore-end */
